#!/usr/bin/env sh
set -e

url="https://raw.githubusercontent.com/webuni/shell-task-runner/master/runner"
[ -f ./.runner ] || wget -q "$url" -O- > .runner || curl -fso .runner "$url"
. ./.runner

! mkdir -p $HOME/.composer/cache
if [ ! -f $HOME/.composer/auth.json ]; then echo "{}" > $HOME/.composer/auth.json; fi

_decorator()( _decorator_docker_compose_run "$@" )

# Install all dependencies
task_deps()( task_composer install 2>&1 )

# Run composer
# @service php
task_composer()( composer "$@" )

# Update dependencies to the latest versions
task_deps__latest()( _run composer update )

# Update dependencies to the lowest versions
task_deps__lowest()( _run composer update --prefer-lowest )

# Run tests
# @service php
task_tests()( "$(__fn phpunit-8 && echo "phpunit-8" || echo "phpunit")" --colors=always "$@" )

# Fix code style
# @service php
task_cs()( php-cs-fixer fix --ansi --allow-risky=yes "$@" )

# Analyse code
# @service php
task_analyse()( phpstan analyse --no-progress --ansi; __fn psalm && psalm || echo '' )

# Remove all containers in project (use -v to remove volumes also)
task_clean()( _docker_compose down --remove-orphans  "$@" )

# Run shell with tools
# @service php
task_tools()( sh "$@" )
